[project]
name = "rl-benchmarking-schema"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.2",
    "stable-baselines3>=2.7.1",
]
